# Generated by Django 3.1.6 on 2021-02-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_do_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='do_date',
            field=models.DateTimeField(null=True),
        ),
    ]
