# Generated by Django 3.1.6 on 2021-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210203_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='do_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
