# Generated by Django 3.1.6 on 2021-02-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20210203_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Temat')),
                ('description', models.TextField(verbose_name='Opis zadania')),
                ('status', models.CharField(choices=[('c', 'Czeka'), ('z', 'Zakończony')], default='c', max_length=1)),
                ('priority', models.CharField(choices=[('w', 'Wysoki'), ('s', 'Średni'), ('n', 'Niski')], max_length=1)),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ('-day', 'priority'),
            },
        ),
        migrations.CreateModel(
            name='TasksDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.DateField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dzień',
                'verbose_name_plural': 'Dni',
                'ordering': ('-day_date',),
                'unique_together': {('day_date', 'owner')},
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.tasksday'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
